### ISSUE TITLE
Installation freeze at 14min remaining

### ISSUE THREAD

**Issue by matthieuduga** [aleixsr/MSI-Prestige-15-A10SC-Hackintosh#1]
Hello,

I follow you guide and went i boot and format SSD to APFS and launch install, at 14min remaining it's freeze and don't create error log on EFI

![thumbnail_IMG_20210218_232232](https://user-images.githubusercontent.com/56045108/108430210-4e7a2300-7241-11eb-89f9-dcdf08bba5e6.jpg)

**Comment by aleixsr** [comment]
Hello, I think it is not an EFI issue, i suggest tou two options:
1) upgrade nvme firmware (I had similar issue with an EVO 970 plus on another laptop)
2) replace usb drive, I know it is an anoyance, but I had issues with that also.

**Comment by aleixsr** [comment]
Him how did you solved it?
