### ISSUE TITLE
Kernel panic after login after moving EFI from USB (created from Windows) to boot drive

### ISSUE THREAD

**Issue by JannickPvP** [aleixsr/MSI-Prestige-15-A10SC-Hackintosh#12]
I always get a kernel panic after moving the EFI from the USB to the boot drive. I removed the Broadcom kexts as I have the Intel AX201. I changed SMBIOS etc. in the config. Any help? Here's a picture of the kernel panic: https://imgur.io/a/rKay3ZD 
The only thing different from my setup to yours is that I have upgraded my RAM to 64GB and I have only one WDC NVMe drive with 512GB.

Edit: I use macOS Ventura (13.6.1)

**Comment by aleixsr** [comment]
Hi,
I'll update EFI soon (this week I hope). 
Currently I'm using a custom version working fine with a lot of changes and improvements.

Any way, did you try to Clean NVRAM?

**Comment by JannickPvP** [comment]
First sorry for the late reply. I kinda wasn't notified that you answered. I just checked just for fun and found out that you replied.
Thanks for the fast update. I'll try it in a few minutes and I'll inform you as soon as possible.

Edit 1: Do I need to change anything because of the more RAM or other NVMe drive?

**Comment by aleixsr** [comment]
No, it should work as is.
When you've confirmed it works for you remember to use GENSMBIOS.

**Comment by JannickPvP** [comment]
I didn't change anything except GenSMBIOS and I'm stuck at this:
![WhatsApp Image 2023-11-11 at 17 09 58_1d7414a7](https://github.com/aleixsr/MSI-Prestige-15-A10SC-Hackintosh/assets/56295020/789ab2ba-7565-46e3-921d-d83fb9a1717c)
I don't know what to do anymore.

**Comment by aleixsr** [comment]
And what happens if you don't modify SMBIOS?

**Comment by lennart808** [comment]
Thank you aleixsr!

IT BOOTS and me and my brother got it Running NOW!

**Comment by aleixsr** [comment]
Then change SMBIOS correctly, do not use mine please.
