### ISSUE TITLE
Thunderbolt Issue on the MSI A10 SC

### ISSUE THREAD

**Issue by lennart808** [aleixsr/MSI-Prestige-15-A10SC-Hackintosh#13]
Hello Guys,

My Specs are:

CPU: Intel Core i7-10710U (Comet Lake)

dGPU: Nvidia GTX 1650 Max-Q (disabled via SSDT)

iGPU: Intel Graphics UHD 630

Display: CMN N156HCE-EN1

NVMe: WDC 512GB

Audio: Realtek ALC298

Wireless: Intel AX-201

Thanks to aleixsr on Github i have a running Hackintosh now with OS version 13.6.1 Ventura!
It is completely stable and boots everytime.

But i can simply not use it because my Thunder Bolt Device "Universal Audio - Apollo Twin X" is not working...
I wanted to create an Hackintosh because my Music Production DAWS and Plugins are not stable enough on Windows.
So I need somebody please to tell me how i can get Thunderbolt working. Otherwise I would have to switch to Windows again.

Usally you connect the device and then give Universal Audio the permisson to use "Accessibility, Microphone" and so on. But it simply not appears.
https://help.uaudio.com/hc/en-us/articles/10378426500372

Any help is appreciated!

Thanks in advance Guys!!

**Comment by aleixsr** [comment]
On "Special Thanks" secion of my readme.md you can found these two links:
https://github.com/KerKerOgh/MSI-Prestige-15-Hackintosh
https://github.com/wgjas2/MSI-Prestige-15-Hackintosh
Maybe they have Thunderbolt working.

**Comment by lennart808** [comment]
thanks for the quick response!!!
Does that mean i need to reinstall everything?

**Comment by aleixsr** [comment]
No, check if they use any kext or SSDT sepcially for Thuderbolt.

**Comment by lennart808** [comment]
I checked they unfortunately they dont.. But do you think this kext could work?
https://github.com/init4/gigabyte-z390-ud-thunderbolt-hackintosh/tree/monterey/EFI/OC/Kexts

**Comment by aleixsr** [comment]
Sorry don't know.
I think ioelectrify is needed but unsure.
