### ISSUE TITLE
HDMI Output Problem

### ISSUE THREAD

**Issue by gemini444** [aleixsr/MSI-Prestige-15-A10SC-Hackintosh#2]
Hi @aleixsr,
I'm using same laptop. I'm booting with your EFI but i HDMI output not works. In my configuration, the screen I'm external monitor is flashing and eventually turns green unfortunately.  
Is it the same for you? Thank you for your efforts.

**Comment by aleixsr** [comment]
I'll check asap.

**Comment by vomesk** [comment]
Same problem. I've realized It works after sleep but I don't get It yo works after boot.

**Comment by vomesk** [comment]
The problem disappears when disable AppleALC.kext, i keep searching.

**Comment by vomesk** [comment]
Solved.

Add or change:
Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > AAPL,ig-platform-id = 0400A53E
Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > device-id = A53E0000 
Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > framebuffer-con0-enable = 01000000
Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > framebuffer-con0-flags = 98000000

Add in boot-args: -igfxblr agdpmod=vit9696

**Comment by aleixsr** [comment]
Thank you very much, I'll test it.
Sorry taking so long but I'm so busy last month...

**Comment by gemini444** [comment]
> Solved.
> 
> Add or change:
> Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > AAPL,ig-platform-id = 0400A53E
> Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > device-id = A53E0000
> Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > framebuffer-con0-enable = 01000000
> Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > framebuffer-con0-flags = 98000000
> 
> Add in boot-args: -igfxblr agdpmod=vit9696

I tested your config @vomesk and it's working fine. Thank you very much your efforts.
And thanks @aleixsr for your EFI.
