### ISSUE TITLE
BT buggy

### ISSUE THREAD

**Issue by aleixsr** [aleixsr/MSI-Prestige-15-A10SC-Hackintosh#3]
BT works and detects BT devices but when you try to connect devices it really doesn't work.

**Comment by vomesk** [comment]
I've got a bt earphones working, but not a keyboard. Also with heliport i have issues with find my mac, sidecar, etc. Ill try to get a native wifi/bt card.

**Comment by aleixsr** [comment]
Fixed in v21.04.20.
