### ISSUE TITLE
Hi, I've problem with boot

### ISSUE THREAD

**Issue by AndryX19** [aleixsr/MSI-Prestige-15-A10SC-Hackintosh#6]
I'm running catalatina running with old efi, what I need to change for showing up opencore and boot windows? Because when I try to boot opencore it show a black screen and then start windows. Thank you for you work.

**Comment by aleixsr** [comment]
Copy Microsoft folder in your EFI and you'll have dual boot.

**Comment by AndryX19** [comment]
The problem is not dual boot, windows 10 boot with it efi folder, the problem is with showing up of opencore, it doesn't appear, black screen, if can help I'm with catalina (needed for some apps compatibility), not bigsur. There's something that I need to change from bigsur configuration to catalina??

**Comment by aleixsr** [comment]
Do you mean that OC is not loading as Boot Manager? If it is the issue, delete EFI folder and copy it again.

**Comment by AndryX19** [comment]
No no, opencore appear in boot menu, if I but opencore I get a black screen and than boot windows, it's strange that not show me boot entries, nothing :(

**Comment by aleixsr** [comment]
Redownload again and copy it again from scatch. If it doesn't work try with older EFI version from my repo.
