### ISSUE TITLE
No audio after rebooting from windows 

### ISSUE THREAD

**Issue by vaqif14** [aleixsr/MSI-Prestige-15-A10SC-Hackintosh#7]
All things work perfectly but only when the first time restart from windows switching to mac sound is missing could you fix pls?

**Comment by aleixsr** [comment]
I know it, 
sorry but I don't know how to fix it. I'll keep this issue open until we find a solution.

Note: Rebooting from scratch works fine.

**Comment by hla63** [comment]
Works with my MSI Modern 15:

swap the Realtek sound driver with the microsoft version under Windows 10.
[Github discution](https://github.com/AndresGarciaSobrado91/MSI-Modern15-Hackintosh/discussions/4)

**Comment by aleixsr** [comment]
Confirmed: Updating drivers using Intel Driver AutoUpdater works.

Thanks.
