### ISSUE TITLE
CNVi locked?

### ISSUE THREAD

**Issue by Dorian1034** [aleixsr/MSI-Prestige-15-A10SC-Hackintosh#8]
This is not an issue related to your efi but I was wondering if you have any difficulties in switching the stock intel wifi chip with broadcom, I have a modern 14 and I can’t get it to recognize a different chip.

**Comment by aleixsr** [comment]
Hi, no I don't have any issues with Broadcom chip. What issue are you getting exactly?

**Comment by Dorian1034** [comment]
Mine does not recognize the chip on bios and because of that I can get it to work on macos and not even windows.

**Comment by aleixsr** [comment]
Did you solved it?
